version: '3'

networks:
  pipiao_network:
    driver: bridge

services:
  redis-dev:
    hostname: redis
    container_name: redis
    image: redis:7.0.10
    volumes:
      - ./redis/data:/data
      - ./redis/logs:/var/log/redis
    networks:
      - pipiao_network
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"

  asynqmon:
    hostname: asynqmon
    container_name: asynqmon
    image: hibiken/asynqmon:latest
    depends_on:
      - redis-dev
    networks:
      - pipiao_network
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "7001:8080"

  etcd0:
    hostname: etcd0
    container_name: etcd0
    image: bitnami/etcd:latest
    volumes:
      - ./etcd/data:/bitnami/etcd
    networks:
      - pipiao_network
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1002
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    ports:
      - "2379:2379"
      - "2380:2380"

  etcdkeeper:
    hostname: etcdkeeper
    container_name: etcdkeeper
    image: evildecay/etcdkeeper:latest
    networks:
      - pipiao_network
    depends_on:
      - etcd0
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "7000:8080"