// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/yguilai/pipiao-bot/app/wfs/internal/conf"
	"github.com/yguilai/pipiao-bot/app/wfs/internal/data"
	"github.com/yguilai/pipiao-bot/app/wfs/internal/server"
	"github.com/yguilai/pipiao-bot/app/wfs/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(logger log.Logger, confServer *conf.Server, confData *conf.Data, registry *conf.Registry) (*kratos.App, func(), error) {
	wfsService := service.NewWfsService()
	grpcServer := server.NewGRPCServer(confServer, wfsService, logger)
	etcdRegistry := data.NewRegistry(registry)
	app := newApp(logger, grpcServer, etcdRegistry)
	return app, func() {
	}, nil
}
