// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/yguilai/pipiao-bot/app/channelbot/internal/biz/handler"
	"github.com/yguilai/pipiao-bot/app/channelbot/internal/conf"
	"github.com/yguilai/pipiao-bot/app/channelbot/internal/data"
	"github.com/yguilai/pipiao-bot/app/channelbot/internal/server"
	"github.com/yguilai/pipiao-bot/app/channelbot/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	asynqServer := data.NewAsynqServer(confData)
	channelBotService := service.NewChannelBotService()
	serverAsynqServer := server.NewAsynqServer(asynqServer, confData, channelBotService, logger)
	client := data.NewAsynqClient(confData)
	messageForwardService := service.NewMessageForwardService(logger, confData, client)
	eventHandler := handler.NewEventHandler(messageForwardService)
	botServer := server.NewBotServer(logger, eventHandler, confData)
	app := newApp(logger, serverAsynqServer, botServer)
	return app, func() {
	}, nil
}
